<a href="https://colab.research.google.com/github/9105507/APRENDIZAJE_AUTOMATICO_23_24/blob/main/0%20INTRODUCCION/0.3.%20Vectores%20y%20matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
lista = [5,6,9,8,7,4,65,2,2,56,46,54]
print(lista)

[5, 6, 9, 8, 7, 4, 65, 2, 2, 56, 46, 54]


In [2]:
2 in lista

True

In [3]:
35 in lista

False

In [4]:
lista[0]

5

In [5]:
lista[-1]

54

In [6]:
lista[2:4]

[9, 8]

In [7]:
lista[:5]

[5, 6, 9, 8, 7]

In [8]:
lista[4:]

[7, 4, 65, 2, 2, 56, 46, 54]

In [9]:
lista[:]

[5, 6, 9, 8, 7, 4, 65, 2, 2, 56, 46, 54]

In [10]:
import numpy as np

# El método arange crea un vector de 'a' a  el nº antes de 'b' --> object.arange(a, b)
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Con object.arange(a, b, n) crea un vector de 'a' a  el nº antes de 'b' dando saltos de 'n' en 'n'
np.arange(1,10,2)


array([1, 3, 5, 7, 9])

In [12]:
# Crea vector a partir de lista
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [13]:
len(a)

4

In [14]:
min(a)

1

In [15]:
max(a)

4

In [18]:
# Con la misma función de antes, crea matriz a partir de varias listas
b = np.array([[1,2,3],[5,6,4],[7,5,2]])
b

array([[1, 2, 3],
       [5, 6, 4],
       [7, 5, 2]])

In [19]:
b[0]

array([1, 2, 3])

In [20]:
b[:,1]

array([2, 6, 5])

In [21]:
b[2,2]

2

# Revisar la indexación de matrices (filas columnas)

In [22]:
b[0:2, 1:3]

array([[2, 3],
       [6, 4]])

In [23]:
a = np.random.rand(5,5)
a

array([[0.41221934, 0.87902097, 0.21001455, 0.25224843, 0.64984575],
       [0.69065835, 0.92436372, 0.2379149 , 0.64112254, 0.77501327],
       [0.81669215, 0.89695529, 0.41995763, 0.09544593, 0.6231384 ],
       [0.98776086, 0.24247104, 0.0827486 , 0.59436357, 0.42782088],
       [0.72051646, 0.67011619, 0.22539802, 0.67454703, 0.86278949]])

In [24]:
a.shape

(5, 5)

In [32]:
b  = np.random.rand(5,5)
b

array([[0.26571039, 0.22756589, 0.78968868, 0.08754208, 0.14285596],
       [0.41764364, 0.59493676, 0.28759896, 0.32889189, 0.77852208],
       [0.83868614, 0.49881852, 0.65679582, 0.29511969, 0.43442612],
       [0.15953775, 0.93703862, 0.10127016, 0.64303248, 0.24608793],
       [0.50853296, 0.64710953, 0.01921943, 0.38772128, 0.62910403]])

In [33]:
a + b

array([[0.67792973, 1.10658685, 0.99970323, 0.33979051, 0.79270171],
       [1.108302  , 1.51930048, 0.52551386, 0.97001443, 1.55353535],
       [1.65537829, 1.39577381, 1.07675345, 0.39056562, 1.05756451],
       [1.14729861, 1.17950966, 0.18401876, 1.23739605, 0.67390881],
       [1.22904942, 1.31722572, 0.24461744, 1.06226831, 1.49189352]])

In [34]:
a-b

array([[ 0.14650895,  0.65145508, -0.57967413,  0.16470635,  0.50698978],
       [ 0.27301471,  0.32942696, -0.04968405,  0.31223066, -0.00350881],
       [-0.02199399,  0.39813677, -0.23683818, -0.19967375,  0.18871228],
       [ 0.82822311, -0.69456757, -0.01852155, -0.04866891,  0.18173295],
       [ 0.21198351,  0.02300666,  0.20617859,  0.28682575,  0.23368546]])

In [35]:
a*b

array([[0.10953096, 0.20003519, 0.16584611, 0.02208235, 0.09283434],
       [0.28844907, 0.54993796, 0.06842408, 0.21086   , 0.60336494],
       [0.68494839, 0.44741791, 0.27582642, 0.02816797, 0.27070759],
       [0.15758515, 0.22720473, 0.00837996, 0.38219508, 0.10528156],
       [0.36640637, 0.43363857, 0.00433202, 0.26153624, 0.54278435]])

In [36]:
a/b

array([[ 1.55138586,  3.86270974,  0.265946  ,  2.88145357,  4.54895778],
       [ 1.65370255,  1.55371761,  0.82724537,  1.94934132,  0.99549299],
       [ 0.97377566,  1.79815956,  0.63940364,  0.32341432,  1.43439442],
       [ 6.1913927 ,  0.25876313,  0.81710748,  0.92431346,  1.73848786],
       [ 1.41685304,  1.03555296, 11.72761354,  1.73977304,  1.37145758]])

In [37]:
np.transpose(a)

array([[0.41221934, 0.69065835, 0.81669215, 0.98776086, 0.72051646],
       [0.87902097, 0.92436372, 0.89695529, 0.24247104, 0.67011619],
       [0.21001455, 0.2379149 , 0.41995763, 0.0827486 , 0.22539802],
       [0.25224843, 0.64112254, 0.09544593, 0.59436357, 0.67454703],
       [0.64984575, 0.77501327, 0.6231384 , 0.42782088, 0.86278949]])

In [38]:
1/a

array([[ 2.42589296,  1.13762929,  4.76157486,  3.96434577,  1.53882672],
       [ 1.44789387,  1.08182523,  4.20318349,  1.55976421,  1.29030048],
       [ 1.22445159,  1.11488278,  2.38119257, 10.47713574,  1.60477994],
       [ 1.01239079,  4.1242038 , 12.08479635,  1.68247189,  2.33742682],
       [ 1.38789334,  1.49227852,  4.4365963 ,  1.48247632,  1.15903127]])

## PROBLEMAS

1. Escribe una función **suma_matrices** que tome dos matrices **NumPy** como argumentos y devuelva una nueva matriz que sea la suma de las dos matrices originales. No utilices la operación de suma incorporada de NumPy (+).

In [47]:
import numpy as np

def suma_matrices(A, B):
  # INTRODUCIR EL CÓDIGO DE LA FUNCIÓN AQUÍ
  # VALIDA QUE LAS MATRICES DE ENTRADA TIENEN LA MISMA DIMENSIÓN
  tam = list(A.shape)
  if list(A.shape) == list(B.shape):
    C  = np.random.rand(tam[0],tam[1])
    for i in range(tam[0]):
      for j in range(tam[1]):
        C[i, j] = A[i, j] + B[i, j]
    return C
  else:
    print("No se pueden sumar dos matrices con dimensiones distintas")
# Pruebas
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
assert np.array_equal(suma_matrices(A, B), np.array([[6, 8], [10, 12]]))

2. Escribe una función **transpuesta** que tome una matriz **NumPy** como argumento y **devuelva su transpuesta**. No utilices la propiedad T de NumPy.

In [50]:
import numpy as np

def transpuesta(A):
  tam = list(A.shape)
  T = np.random.rand(tam[1], tam[0])
  for i in range(tam[1]):
      for j in range(tam[0]):
        T[i, j] = A[j, i]
  return T

# Pruebas
A = np.array([[1, 2, 3], [4, 5, 6]])
assert np.array_equal(transpuesta(A), np.array([[1, 4], [2, 5], [3, 6]]))

[[1. 4.]
 [2. 5.]
 [3. 6.]]


3. Escribe una función **multiplicar_matrices** que tome dos matrices **NumPy** como argumentos y devuelva una nueva matriz que sea el resultado de la multiplicación de las dos matrices originales. No utilices la operación de multiplicación de matrices incorporada de NumPy (@ o np.dot).

In [ ]:
import numpy as np

def multiplicar_matrices(A, B):
  # INTRODUCIR EL CÓDIGO DE LA FUNCIÓN AQUÍ
  # VALIDA QUE LAS MATRICES DE ENTRADA TIENEN LAS DIMENSIONES
  # ADECUADAS QUE PERMITEN LA MULTIPLICACIÓN MATRICIAL

# Pruebas
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])
assert np.array_equal(multiplicar_matrices(A, B), np.array([[4, 4], [10, 8]]))