<a href="https://colab.research.google.com/github/9105507/APRENDIZAJE_AUTOMATICO_23_24/blob/main/0%20INTRODUCCION/0.3.%20Vectores%20y%20matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
lista = [5,6,9,8,7,4,65,2,2,56,46,54]
print(lista)

[5, 6, 9, 8, 7, 4, 65, 2, 2, 56, 46, 54]


In [2]:
2 in lista

True

In [3]:
35 in lista

False

In [4]:
lista[0]

5

In [5]:
lista[-1]

54

In [6]:
lista[2:4]

[9, 8]

In [7]:
lista[:5]

[5, 6, 9, 8, 7]

In [8]:
lista[4:]

[7, 4, 65, 2, 2, 56, 46, 54]

In [9]:
lista[:]

[5, 6, 9, 8, 7, 4, 65, 2, 2, 56, 46, 54]

In [10]:
import numpy as np

# El método arange crea un vector de 'a' a  el nº antes de 'b' --> object.arange(a, b)
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Con object.arange(a, b, n) crea un vector de 'a' a  el nº antes de 'b' dando saltos de 'n' en 'n'
np.arange(1,10,2)


array([1, 3, 5, 7, 9])

In [12]:
# Crea vector a partir de lista
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [13]:
len(a)

4

In [14]:
min(a)

1

In [15]:
max(a)

4

In [16]:
# Con la misma función de antes, crea matriz a partir de varias listas
b = np.array([[1,2,3],[5,6,4],[7,5,2]])
b

array([[1, 2, 3],
       [5, 6, 4],
       [7, 5, 2]])

In [17]:
b[0]

array([1, 2, 3])

In [18]:
b[:,1]

array([2, 6, 5])

In [19]:
b[2,2]

2

# Revisar la indexación de matrices (filas columnas)

In [20]:
b[0:2, 1:3]

array([[2, 3],
       [6, 4]])

In [21]:
a = np.random.rand(5,5)
a

array([[0.94400519, 0.87251361, 0.29478401, 0.46874292, 0.69081303],
       [0.17813162, 0.04966955, 0.42384476, 0.13154357, 0.65866205],
       [0.68229362, 0.20339743, 0.83452197, 0.70352547, 0.19476513],
       [0.16328618, 0.87241844, 0.16363131, 0.24769825, 0.42734238],
       [0.5850279 , 0.86019604, 0.67156141, 0.22041341, 0.24996767]])

In [22]:
a.shape

(5, 5)

In [23]:
b  = np.random.rand(5,5)
b

array([[0.67576015, 0.27309039, 0.24903091, 0.77414727, 0.21212312],
       [0.46387382, 0.96916769, 0.30861405, 0.39951042, 0.82506299],
       [0.28903622, 0.79351292, 0.27998127, 0.54065376, 0.36035261],
       [0.25376043, 0.74942927, 0.05660787, 0.34210154, 0.61054411],
       [0.58509224, 0.68887613, 0.07684128, 0.83715243, 0.11701405]])

In [24]:
a + b

array([[1.61976534, 1.14560401, 0.54381492, 1.24289018, 0.90293615],
       [0.64200545, 1.01883724, 0.7324588 , 0.531054  , 1.48372503],
       [0.97132984, 0.99691035, 1.11450323, 1.24417923, 0.55511774],
       [0.41704661, 1.62184772, 0.22023917, 0.58979978, 1.03788649],
       [1.17012015, 1.54907218, 0.74840269, 1.05756584, 0.36698173]])

In [25]:
a-b

array([[ 2.68245036e-01,  5.99423223e-01,  4.57531071e-02,
        -3.05404348e-01,  4.78689903e-01],
       [-2.85742200e-01, -9.19498137e-01,  1.15230708e-01,
        -2.67966853e-01, -1.66400941e-01],
       [ 3.93257400e-01, -5.90115490e-01,  5.54540701e-01,
         1.62871708e-01, -1.65587487e-01],
       [-9.04742545e-02,  1.22989169e-01,  1.07023443e-01,
        -9.44032888e-02, -1.83201734e-01],
       [-6.43419141e-05,  1.71319911e-01,  5.94720124e-01,
        -6.16739021e-01,  1.32953621e-01]])

In [26]:
a*b

array([[0.63792109, 0.23827508, 0.07341033, 0.36287605, 0.14653742],
       [0.0826306 , 0.04813812, 0.13080445, 0.05255303, 0.54343768],
       [0.19720757, 0.16139849, 0.23365052, 0.38036369, 0.07018412],
       [0.04143557, 0.65381592, 0.00926282, 0.08473795, 0.26091137],
       [0.34229529, 0.59256853, 0.05160364, 0.18451962, 0.02924973]])

In [27]:
a/b

array([[1.39695302, 3.1949627 , 1.18372461, 0.6054958 , 3.25666062],
       [0.38400879, 0.0512497 , 1.37338128, 0.32926193, 0.79831729],
       [2.36058173, 0.25632529, 2.98063502, 1.30124956, 0.54048485],
       [0.64346587, 1.16411044, 2.89061083, 0.72404892, 0.69993694],
       [0.99989003, 1.2486948 , 8.73959132, 0.26328946, 2.13621927]])

In [28]:
np.transpose(a)

array([[0.94400519, 0.17813162, 0.68229362, 0.16328618, 0.5850279 ],
       [0.87251361, 0.04966955, 0.20339743, 0.87241844, 0.86019604],
       [0.29478401, 0.42384476, 0.83452197, 0.16363131, 0.67156141],
       [0.46874292, 0.13154357, 0.70352547, 0.24769825, 0.22041341],
       [0.69081303, 0.65866205, 0.19476513, 0.42734238, 0.24996767]])

In [29]:
1/a

array([[ 1.05931621,  1.14611392,  3.39231421,  2.13336556,  1.44756969],
       [ 5.61382632, 20.13305975,  2.35935443,  7.60204385,  1.51822927],
       [ 1.46564466,  4.91648296,  1.19829081,  1.42141265,  5.13438935],
       [ 6.12421703,  1.14623895,  6.11129993,  4.03717028,  2.34004409],
       [ 1.70932018,  1.16252569,  1.48906711,  4.53692903,  4.00051729]])

## PROBLEMAS

1. Escribe una función **suma_matrices** que tome dos matrices **NumPy** como argumentos y devuelva una nueva matriz que sea la suma de las dos matrices originales. No utilices la operación de suma incorporada de NumPy (+).

In [33]:
import numpy as np

def suma_matrices(A, B):
  tam = list(A.shape)
  if list(A.shape) == list(B.shape):
    C  = np.random.rand(tam[0],tam[1])
    for i in range(tam[0]):
      for j in range(tam[1]):
        C[i, j] = A[i, j] + B[i, j]
    return C
  else:
    print("No se pueden sumar dos matrices con dimensiones distintas")
# Pruebas
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
assert np.array_equal(suma_matrices(A, B), np.array([[6, 8], [10, 12]]))

2. Escribe una función **transpuesta** que tome una matriz **NumPy** como argumento y **devuelva su transpuesta**. No utilices la propiedad T de NumPy.

In [35]:
import numpy as np

def transpuesta(A):
  tam = list(A.shape)
  T = np.random.rand(tam[1], tam[0])
  for i in range(tam[1]):
      for j in range(tam[0]):
        T[i, j] = A[j, i]
  return T

# Pruebas
A = np.array([[1, 2, 3], [4, 5, 6]])
assert np.array_equal(transpuesta(A), np.array([[1, 4], [2, 5], [3, 6]]))
print(transpuesta(A))

[[1. 4.]
 [2. 5.]
 [3. 6.]]


3. Escribe una función **multiplicar_matrices** que tome dos matrices **NumPy** como argumentos y devuelva una nueva matriz que sea el resultado de la multiplicación de las dos matrices originales. No utilices la operación de multiplicación de matrices incorporada de NumPy (@ o np.dot).

In [37]:
import numpy as np

def multiplicar_matrices(A, B):
  tamA = list(A.shape)
  tamB = list(B.shape)
  if tamA[1] == tamB[0]:
    C  = np.random.rand(tamA[0],tamB[1])
    for i in range(tamA[0]):
      for j in range(tamB[1]):
        x = 0
        for k in range(tamA[1]):
          x = x + A[i,k]*B[k,j]
        C[i,j] = x
    return C
  else:
    print("Las dimensiones de estas matrices no son adecuadas para la multiplicación matricial.")

# Pruebas
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])
assert np.array_equal(multiplicar_matrices(A, B), np.array([[4, 4], [10, 8]]))
print(multiplicar_matrices(A, B))

[[ 4.  4.]
 [10.  8.]]
